"""Initial Migration

Revision ID: 26768deb551e
Revises: 
Create Date: 2024-11-18 10:31:09.435502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26768deb551e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availabilities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('doctorId', sa.String(length=50), nullable=False),
    sa.Column('availableFrom', sa.DateTime(), nullable=False),
    sa.Column('availableTo', sa.DateTime(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patientId', sa.String(), nullable=False),
    sa.Column('doctorId', sa.String(), nullable=False),
    sa.Column('availabilityId', sa.String(), nullable=False),
    sa.Column('appointmentDateTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['availabilityId'], ['availabilities.id'], ),
    sa.ForeignKeyConstraint(['doctorId'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['patientId'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('appointmentId', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointmentId'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('appointments')
    op.drop_table('users')
    op.drop_table('availabilities')
    # ### end Alembic commands ###
