"""appointment datetime updated

Revision ID: 65babb1de6c1
Revises: fed72b4bdf2e
Create Date: 2024-11-18 11:14:38.848087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65babb1de6c1'
down_revision = 'fed72b4bdf2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_from', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('appointment_to', sa.DateTime(), nullable=False))
        batch_op.drop_column('appointmentDateTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointmentDateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('appointment_to')
        batch_op.drop_column('appointment_from')

    # ### end Alembic commands ###
